Traceback (most recent call last):
  File "random.py", line 2, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python2.7/site-packages/keras/backend/__init__.py", line 6, in <module>
    from .common import epsilon
  File "/usr/local/lib/python2.7/site-packages/keras/backend/common.py", line 1, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 21, in <module>
    from .utils import SkipTest
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/local/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/workdir/current/random.py", line 2, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 8, in <module>
    from . import backend as K
ImportError: cannot import name backend
